/**
 * Contact Service — Dataverse data access layer.
 *
 * Uses the official Code Apps SDK generated by:
 *   pac code add-data-source -a dataverse -t contact
 *
 * The generated ContactsService talks to Dataverse through the
 * Power Apps host runtime (user-delegated auth) — no Web API
 * calls, no client secrets, no MSAL. All data access flows
 * through the @microsoft/power-apps SDK.
 */

import type { Contact, ContactFormData } from "../types";
import { ContactsService } from "../generated/services/ContactsService";
import type { Contacts, ContactsBase } from "../generated/models/ContactsModel";

// ── Field list used for $select ──────────────────────────────────
// IMPORTANT: field names here must match the Dataverse logical names
// exactly. Invalid names cause the SDK to silently return empty.
// - "company" NOT "companyname" (checked against ContactsModel.ts)
// - "fullname" is computed/read-only — returned automatically, omit from $select
// - "mj_primarystore" is a lookup (object) — omit from $select to avoid errors
const CONTACT_SELECT_FIELDS = [
  "contactid",
  "firstname",
  "lastname",
  "jobtitle",
  "department",
  "emailaddress1",
  "emailaddress2",
  "telephone1",
  "telephone2",
  "mobilephone",
  "fax",
  "websiteurl",
  "preferredcontactmethodcode",
  "address1_line1",
  "address1_line2",
  "address1_line3",
  "address1_city",
  "address1_stateorprovince",
  "address1_postalcode",
  "address1_country",
  "company",
  "statecode",
  "statuscode",
  "createdon",
  "modifiedon",
  // mj_ custom energy fields
  "mj_analysislastrun",
  "mj_boilermake",
  "mj_boilermodel",
  "mj_conversationlogic",
  "mj_conversationpoints",
  "mj_doyouhaveahivethermostat",
  "mj_doyouhaveasmartmeter",
  "mj_doyouhavesmartradiatorvalves",
  "mj_energytariff",
  "mj_homecarecover",
  "mj_homecaretypeofcover",
  "mj_homeevcharger",
  "mj_initiateoutboundcall",
  "mj_installationdate",
  "mj_priorityregister",
  "mj_refreshanalysis",
  "mj_repairedrecently",
  "mj_smartmeter",
  "mj_utility_ev_owner",
];

// ── Chris Walker fallback GUID ───────────────────────────────────
/** Real Chris Walker GUID from D365. */
export const CHRIS_WALKER_ID = "7fba73b9-2461-ef11-bfe2-002248a36d0e";

// ── Type conversion helpers ──────────────────────────────────────
// Dataverse BIT fields are Edm.Boolean — the OData API expects
// true/false, NOT 0/1 integers. The SDK type aliases use 0|1 as
// TypeScript keys but the wire format must be native booleans.

/** SDK boolean-ish → boolean (treats undefined/null/0 as false) */
function toBool(v: 0 | 1 | boolean | undefined | null): boolean {
  return v === 1 || v === true;
}

/** boolean → Dataverse Edm.Boolean (true/false, not 0/1) */
function toEdmBool(v: boolean | undefined): boolean {
  return v === true;
}

/** Map a Dataverse SDK Contacts record → our local Contact type. */
function toContact(c: Contacts): Contact {
  return {
    contactid: c.contactid,
    firstname: c.firstname,
    lastname: c.lastname,
    fullname: c.fullname,
    jobtitle: c.jobtitle,
    department: c.department,
    emailaddress1: c.emailaddress1,
    emailaddress2: c.emailaddress2,
    telephone1: c.telephone1,
    telephone2: c.telephone2,
    mobilephone: c.mobilephone,
    fax: c.fax,
    websiteurl: c.websiteurl,
    preferredcontactmethodcode:
      c.preferredcontactmethodcode as unknown as number,
    address1_line1: c.address1_line1,
    address1_line2: c.address1_line2,
    address1_line3: c.address1_line3,
    address1_city: c.address1_city,
    address1_stateorprovince: c.address1_stateorprovince,
    address1_postalcode: c.address1_postalcode,
    address1_country: c.address1_country,
    companyname: c.company,
    statecode: c.statecode as unknown as number,
    statuscode: c.statuscode as unknown as number,
    createdon: c.createdon,
    modifiedon: c.modifiedon,
    // mj_ energy fields — convert 0/1 → boolean
    mj_analysislastrun: c.mj_analysislastrun,
    mj_boilermake: c.mj_boilermake as unknown as number,
    "mj_boilermake@OData.Community.Display.V1.FormattedValue":
      c.mj_boilermakename,
    mj_boilermodel: c.mj_boilermodel,
    mj_conversationlogic: c.mj_conversationlogic,
    mj_conversationpoints: c.mj_conversationpoints,
    mj_doyouhaveahivethermostat: toBool(
      c.mj_doyouhaveahivethermostat as unknown as 0 | 1,
    ),
    mj_doyouhaveasmartmeter: toBool(
      c.mj_doyouhaveasmartmeter as unknown as 0 | 1,
    ),
    mj_doyouhavesmartradiatorvalves: toBool(
      c.mj_doyouhavesmartradiatorvalves as unknown as 0 | 1,
    ),
    mj_energytariff: c.mj_energytariff as unknown as number,
    "mj_energytariff@OData.Community.Display.V1.FormattedValue":
      c.mj_energytariffname,
    mj_homecarecover: toBool(c.mj_homecarecover as unknown as 0 | 1),
    mj_homecaretypeofcover: c.mj_homecaretypeofcover as unknown as number,
    "mj_homecaretypeofcover@OData.Community.Display.V1.FormattedValue":
      c.mj_homecaretypeofcovername,
    mj_homeevcharger: toBool(c.mj_homeevcharger as unknown as 0 | 1),
    mj_initiateoutboundcall: toBool(
      c.mj_initiateoutboundcall as unknown as 0 | 1,
    ),
    mj_installationdate: c.mj_installationdate,
    mj_priorityregister: toBool(c.mj_priorityregister as unknown as 0 | 1),
    mj_refreshanalysis: toBool(c.mj_refreshanalysis as unknown as 0 | 1),
    mj_repairedrecently: toBool(c.mj_repairedrecently as unknown as 0 | 1),
    mj_smartmeter: toBool(c.mj_smartmeter as unknown as 0 | 1),
    mj_utility_ev_owner: toBool(c.mj_utility_ev_owner as unknown as 0 | 1),
    // Owner (read-only)
    _ownerid_value: c._owninguser_value,
    "_ownerid_value@OData.Community.Display.V1.FormattedValue": c.owneridname,
  };
}

// ── Service facade ───────────────────────────────────────────────

/**
 * Retrieves all active contacts.
 */
export async function getAllContacts(options?: {
  filter?: string;
  top?: number;
  orderBy?: string[];
}): Promise<Contact[]> {
  const result = await ContactsService.getAll({
    select: CONTACT_SELECT_FIELDS,
    filter: options?.filter ?? "statecode eq 0",
    orderBy: options?.orderBy ?? ["fullname asc"],
    top: options?.top ?? 100,
  });
  return (result.data ?? []).map(toContact);
}

/**
 * Retrieves a single contact by ID.
 * Falls back to Chris Walker if no ID provided.
 */
export async function getContactById(
  contactId?: string,
): Promise<Contact | null> {
  const resolvedId = contactId ?? CHRIS_WALKER_ID;

  // Attempt 1: No $select — get all fields, maximum compatibility
  let result: unknown;
  try {
    result = await ContactsService.get(resolvedId);
  } catch (sdkError) {
    const msg = sdkError instanceof Error ? sdkError.message : String(sdkError);
    throw new Error(`SDK get(${resolvedId}) failed: ${msg}`);
  }

  // The SDK IOperationResult should have { data: Contacts }
  // but the shape may differ — inspect all possibilities
  const operationResult = result as Record<string, unknown> | null;

  // Store debug info globally so the page can display it
  (window as unknown as Record<string, unknown>).__sdkDebug = {
    resultType: typeof result,
    resultIsNull: result === null || result === undefined,
    resultKeys: operationResult ? Object.keys(operationResult) : [],
    hasData:
      operationResult?.data !== undefined && operationResult?.data !== null,
    hasValue: operationResult?.value !== undefined,
    hasRecord: operationResult?.record !== undefined,
    dataType: typeof operationResult?.data,
    rawSnippet: JSON.stringify(result, null, 2)?.slice(0, 3000) ?? "(null)",
  };

  // Try all known shapes the SDK might return
  let contactData: Contacts | null = null;
  if (operationResult?.data) {
    contactData = operationResult.data as Contacts;
  } else if (operationResult && "contactid" in operationResult) {
    // The result IS the contact directly (no wrapper)
    contactData = operationResult as unknown as Contacts;
  } else if (operationResult?.value) {
    // Array wrapper
    const arr = operationResult.value as Contacts[];
    contactData = arr.length > 0 ? arr[0] : null;
  } else if (operationResult?.record) {
    contactData = operationResult.record as Contacts;
  }

  return contactData ? toContact(contactData) : null;
}

/**
 * Retrieves a contact by name (used for fallback when no ID argument).
 */
export async function getContactByName(
  firstName: string,
  lastName: string,
): Promise<Contact | null> {
  const result = await ContactsService.getAll({
    select: CONTACT_SELECT_FIELDS,
    filter: `firstname eq '${firstName}' and lastname eq '${lastName}'`,
    top: 1,
  });
  const records = result.data ?? [];
  return records.length > 0 ? toContact(records[0]) : null;
}

/**
 * Creates a new contact and returns the created record.
 */
export async function createContact(data: ContactFormData): Promise<Contact> {
  const payload: Partial<ContactsBase> = {
    firstname: data.firstname,
    lastname: data.lastname ?? "Unknown",
    jobtitle: data.jobtitle,
    department: data.department,
    emailaddress1: data.emailaddress1,
    telephone1: data.telephone1,
    mobilephone: data.mobilephone,
    address1_line1: data.address1_line1,
    address1_city: data.address1_city,
    address1_postalcode: data.address1_postalcode,
    address1_country: data.address1_country,
  };
  const result = await ContactsService.create(
    payload as Omit<ContactsBase, "address1_addressid">,
  );
  return toContact(result.data!);
}

/**
 * Updates an existing contact — writes changed fields to Dataverse.
 */
export async function updateContact(
  contactId: string,
  changes: Partial<ContactFormData>,
): Promise<void> {
  // Build SDK-compatible payload, converting booleans → 0/1
  const payload: Record<string, unknown> = {};

  // String fields — pass through
  if (changes.mj_boilermodel !== undefined)
    payload.mj_boilermodel = changes.mj_boilermodel;
  if (changes.mj_installationdate !== undefined)
    payload.mj_installationdate = changes.mj_installationdate;
  if (changes.mj_conversationpoints !== undefined)
    payload.mj_conversationpoints = changes.mj_conversationpoints;
  if (changes.mj_conversationlogic !== undefined)
    payload.mj_conversationlogic = changes.mj_conversationlogic;

  // Choice fields — pass as numbers
  if (changes.mj_boilermake !== undefined)
    payload.mj_boilermake = changes.mj_boilermake;
  if (changes.mj_energytariff !== undefined)
    payload.mj_energytariff = changes.mj_energytariff;
  if (changes.mj_homecaretypeofcover !== undefined)
    payload.mj_homecaretypeofcover = changes.mj_homecaretypeofcover;

  // Two-Option (boolean) fields — Dataverse expects true/false
  if (changes.mj_homecarecover !== undefined)
    payload.mj_homecarecover = toEdmBool(changes.mj_homecarecover);
  if (changes.mj_smartmeter !== undefined)
    payload.mj_smartmeter = toEdmBool(changes.mj_smartmeter);
  if (changes.mj_doyouhaveasmartmeter !== undefined)
    payload.mj_doyouhaveasmartmeter = toEdmBool(
      changes.mj_doyouhaveasmartmeter,
    );
  if (changes.mj_doyouhaveahivethermostat !== undefined)
    payload.mj_doyouhaveahivethermostat = toEdmBool(
      changes.mj_doyouhaveahivethermostat,
    );
  if (changes.mj_doyouhavesmartradiatorvalves !== undefined)
    payload.mj_doyouhavesmartradiatorvalves = toEdmBool(
      changes.mj_doyouhavesmartradiatorvalves,
    );
  if (changes.mj_utility_ev_owner !== undefined)
    payload.mj_utility_ev_owner = toEdmBool(changes.mj_utility_ev_owner);
  if (changes.mj_homeevcharger !== undefined)
    payload.mj_homeevcharger = toEdmBool(changes.mj_homeevcharger);
  if (changes.mj_priorityregister !== undefined)
    payload.mj_priorityregister = toEdmBool(changes.mj_priorityregister);
  if (changes.mj_repairedrecently !== undefined)
    payload.mj_repairedrecently = toEdmBool(changes.mj_repairedrecently);

  console.log(
    "[ContactService] updateContact payload:",
    JSON.stringify(payload, null, 2),
  );

  // Store debug info for the UI
  const saveDebug: Record<string, unknown> = {
    contactId,
    payloadKeys: Object.keys(payload),
    payloadFieldCount: Object.keys(payload).length,
    payload,
  };

  try {
    const result = await ContactsService.update(
      contactId,
      payload as Partial<Omit<ContactsBase, "address1_addressid">>,
    );
    const res = result as unknown as Record<string, unknown>;
    saveDebug.resultType = typeof result;
    saveDebug.resultKeys = res ? Object.keys(res) : [];
    saveDebug.resultSnippet = JSON.stringify(result, null, 2)?.slice(0, 1000);

    // The SDK may return { success: false, error: {...} } without throwing
    if (res?.success === false && res?.error) {
      const errObj = res.error as Record<string, unknown>;
      const errMsg = (errObj.message as string) ?? JSON.stringify(errObj);
      saveDebug.success = false;
      saveDebug.error = errMsg;
      (window as unknown as Record<string, unknown>).__sdkSaveDebug = saveDebug;
      throw new Error(`Dataverse update failed: ${errMsg.slice(0, 300)}`);
    }

    saveDebug.success = true;
    (window as unknown as Record<string, unknown>).__sdkSaveDebug = saveDebug;
    console.log("[ContactService] Update result:", result);
  } catch (sdkError) {
    saveDebug.success = false;
    saveDebug.error =
      sdkError instanceof Error ? sdkError.message : String(sdkError);
    saveDebug.errorStack =
      sdkError instanceof Error ? sdkError.stack : undefined;
    (window as unknown as Record<string, unknown>).__sdkSaveDebug = saveDebug;
    console.error("[ContactService] Update failed:", sdkError);
    throw sdkError;
  }
}

/**
 * Deletes a contact by ID.
 */
export async function deleteContact(contactId: string): Promise<void> {
  await ContactsService.delete(contactId);
}
